<a href="https://colab.research.google.com/github/Rena03528/understanding_AI/blob/main/Pytorch_Fundametals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print("Hello, let's learn pytorch!")

2.10.0+cu128
Hello, let's learn pytorch!


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar.item())
print(scalar)

7
tensor(7)


In [ ]:
# vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [ ]:
# matrix
matrix = torch.tensor([[7,8],[1,2]])
matrix

tensor([[7, 8],
        [1, 2]])

In [ ]:
# tensor
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
print(tensor.ndim)
print(tensor.shape)

# explicacao do shape [1,3,3]
# 1 -> referente ao numero de elementos dentro do primeiro parenteses (apenas um vetor azul)
# 3 -> referente ao numero de elemnetos dentro do segundo parenteses (3 vetores amarelos)
# 3 -> referente ao numero de elementos dentro do parenteses amarelos (3 valores)

3
torch.Size([1, 3, 3])


## Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4933, 0.6379, 0.2779, 0.9223],
        [0.0344, 0.7039, 0.7744, 0.4394],
        [0.0062, 0.4755, 0.3382, 0.1895]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# check data type
ones.dtype

torch.float32

### Creating a range of sensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(start=1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

 **Note:** Tensor datatypes is one of the 3 big erros you'll run into with PyTorch & Deep Learning:

 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # datatype of the tensor
                               device=None, # cuda,cpu -> What device is your tensor on
                               requires_grad=False) # if we want the pytorch to track the gradient of the tensor

# these are the most important parameters while creating a tensor

# datatype is derectly correlated witrh the precision in computer science.
# The more amount of bits the more detailed is the number storage
# The most common values are 32 and 16 bits.
# More bits -> more detailed and more memory
# Less bits -> Less detailed and less memory

In [ ]:
#default datatype is float 32
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

 1. Tensors not right datatype -> to get datatype from a tensor, can use `tensor.dtype`
 2. Tensors not right shape -> to get shape from a tensor, can use `tensor.shape`
 3. Tensors not on the right device -> to get device from a tensor, can use `tensor.device`


In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6094, 0.9149, 0.1834, 0.9163],
        [0.0911, 0.0587, 0.6215, 0.3360],
        [0.5536, 0.0960, 0.9988, 0.1014]])

In [ ]:
# they return the same result. One is a function and the other an atribute
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

Tensor operations include:
* Adition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication


In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor = tensor * 10

In [ ]:
# Subtract tensor by 10
tensor = tensor - 10

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([  0, 100, 200])

In [ ]:
torch.add(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.sub(tensor,10)

tensor([-10,   0,  10])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Rules while performing matrix multiplication:
1. The inner dimensions should match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Element wise multiplication
print(tensor, "*" , tensor)
print(f"Equals: {tensor * tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals: tensor([  0, 100, 400])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(500)

### One of the most common errors in deep learning: shape errors


In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using the transpose

In [ ]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (tensor aggregation)


In [ ]:
x = torch.arange(0,100,10)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.dtype

torch.int64

In [ ]:
# the mean function dont work with int value. We need to convert to float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[0],x[9]

(tensor(0), tensor(90))

# Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape bnut keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all l dimensions from a tensor
* Unsqueeze - removes all l dimenion to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

# note the number os elements has to stay the same

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# the view shares the same memory as the original tensor
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# squeeze - remove all single dimensions from a target tensor
x_reshaped

tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [ ]:
x_reshaped.shape

torch.Size([10, 1])

In [ ]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# it removes all single dimensions
x_reshaped.squeeze().shape

torch.Size([10])

In [ ]:
# Permute - rearanges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour channels]

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing wirh NumPy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the most inner bracket
x[0,0,0]

tensor(1)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all the values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all value of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values od 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index to x to return 3,6,9
x[:,:,2], x[0,:,2]

(tensor([[3, 6, 9]]), tensor([3, 6, 9]))

## Pytorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`








In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> PyTorch reflects numpy's default dataype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to NumPy tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to make random out of random)

In short how neural newtwork learns:

`start with random numbers -> tensor operations -> update random number and make them better representations of the data -> again -> again ...`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**

In [ ]:
import torch

# crate two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8011, 0.1451, 0.2140, 0.3694],
        [0.4716, 0.3488, 0.9034, 0.1746],
        [0.0200, 0.8905, 0.0314, 0.8352]])
tensor([[0.2064, 0.1726, 0.0790, 0.8571],
        [0.2468, 0.1960, 0.9763, 0.6829],
        [0.1401, 0.4589, 0.8887, 0.2351]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Letºs make random but reproducible tensors

import torch

# Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computatuon on numbers, thanks to cuda + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory :)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes a little bit of setup and requires the investment od purchasing a GPU
3. Use cloud computing - CGP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU Drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

### 2. Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations


In [ ]:
tensor = torch.tensor([1,2,3], device = "cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Movig tensor back to CPU


In [ ]:
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Exercises and  ExtraCurriculum

In [ ]:
import torch

In [ ]:
# 2. Create a random tensor with shape (7,7)

random_tensor = torch.rand(7,7)
random_tensor, random_tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

In [ ]:
# 3. Perfome a matrix multiplication
another_random_tensor = torch.rand(1,7)

result = torch.mm(random_tensor, another_random_tensor.T)
result, result.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [ ]:
# 4. Set random_seed to 0 and repeat 2) and 3)

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

notsorandom_tensor = torch.rand(7,7)
another_notsorandom_tensor = torch.rand(1,7)

result = torch.mm(notsorandom_tensor, another_notsorandom_tensor.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
# 5. Set random seed on GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

In [ ]:
# 6. Create to random tensor and send them both to the GPU

# set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
random_tensor_A_on_gpu = torch.rand(2,3).to(device)
random_tensor_B_on_gpu = torch.rand(2,3).to(device)

random_tensor_A_on_gpu, random_tensor_B_on_gpu


(tensor([[0.0340, 0.9442, 0.8802],
         [0.0012, 0.5936, 0.4158]], device='cuda:0'),
 tensor([[0.4177, 0.2711, 0.6923],
         [0.2038, 0.6833, 0.7529]], device='cuda:0'))

In [ ]:
# 7. Perform a matrix multiplication on the tensors created on 6)

result = torch.mm(random_tensor_A_on_gpu, random_tensor_B_on_gpu.T)
result, result.shape

(tensor([[0.8795, 1.3148],
         [0.4493, 0.7189]], device='cuda:0'),
 torch.Size([2, 2]))

In [ ]:
# 8. Find the max and min on the result obtained in 7)

max_value = result.max()
min_value = result.min()

max_value, min_value

(tensor(1.3148, device='cuda:0'), tensor(0.4493, device='cuda:0'))

In [ ]:
# 9. Find the maximum and minimum index value of the result obtained in 7)

max_index = result.argmax()
min_index = result.argmin()

max_index, min_index

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))

In [ ]:
# Exercise 10.

# set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# create random tensor
tensor_1 = torch.rand(1,1,1,10)

# remove single dimensions
tensor_1 = tensor_1.squeeze()

# Print our tensors and their shapes
tensor_1, tensor_1.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))